network:
  ethernets:
    eth0:
      dhcp4: false
      addresses:
        [192.168.2.10/24]
  wifis:
    wlan0:
      optional: true
      access-points:
        "Jakob - iPhone":
          password: "Jakobbok"
      dhcp4: true
