#!/usr/bin/env python
#################################################################################
# Copyright 2018 ROBOTIS CO., LTD.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#################################################################################

# Authors: Gilbert #

import rospy
import math
import statistics
from sensor_msgs.msg import LaserScan
from geometry_msgs.msg import Twist
import readFromRGB

LINEAR_VEL = 0.21 #MAX = 0.21, MAX ANG.Z=2.6
LINEAR_PERCENT = LINEAR_VEL/100
ANGULAR_VEL = 2.6
ANGULAR_PERCENT = ANGULAR_VEL/100
STOP_DISTANCE = 0.10
LIDAR_ERROR = 0.05
SAFE_STOP_DISTANCE = STOP_DISTANCE + LIDAR_ERROR
FULL_SEND_DISTANCE = SAFE_STOP_DISTANCE * 3

LEFT = 1
RIGHT = -1

class Obstacle():
    def __init__(self):
        self._cmd_pub = rospy.Publisher('cmd_vel', Twist, queue_size=1)
        self.obstacle()

    def turn(self, direction, distance, back_up = False):
        linear_skew = abs((distance - FULL_SEND_DISTANCE) / (FULL_SEND_DISTANCE))
        angular_skew = 100 - linear_skew
        
        # Direction changes parity of angular vel to turn left or right
        if not back_up:
            return linear_skew * LINEAR_PERCENT, direction * angular_skew * ANGULAR_PERCENT
        else:
            return -linear_skew * LINEAR_PERCENT, -direction * angular_skew * ANGULAR_PERCENT
        
    def get_scan(self):
        scan = rospy.wait_for_message('scan', LaserScan)
        scan_filter = []
        
        samples = len(scan.ranges)  # The number of samples is defined in 
                                    # turtlebot3_<model>.gazebo.xacro file,
                                    # the default is 360.
        samples_view = 90           # 1 <= samples_view <= samples
        
        if samples_view > samples:
            samples_view = samples

        if samples_view is 1:
            scan_filter.append(scan.ranges[0])

        else:
            left_lidar_samples_ranges = -(samples_view//2 + samples_view % 2)
            right_lidar_samples_ranges = samples_view//2
            
            left_lidar_samples = scan.ranges[left_lidar_samples_ranges:]
            right_lidar_samples = scan.ranges[:right_lidar_samples_ranges]
            scan_filter.extend(left_lidar_samples + right_lidar_samples)

        for i in range(samples_view):
            if scan_filter[i] == float('Inf'):
                scan_filter[i] = 3.5
            elif math.isnan(scan_filter[i]):
                scan_filter[i] = 0
        
        return scan_filter

    def obstacle(self):
        twist = Twist()

        while not rospy.is_shutdown():
            lidar_distances = self.get_scan()
            statistics.mean(lidar_distances)
            angles = []
            distances = []
            for i in range(6):
                theta = i * 30
                angles = angles.append(theta)
                distances.append(statistics.mean(lidar_distances[theta:theta+30]))

            if distances[2] < SAFE_STOP_DISTANCE: # 60°-90°
                twist.linear.x, twist.angular.z = self.turn(LEFT, distances[2], back_up = True)
                self._cmd_pub.publish(twist)
                rospy.loginfo(f'Too close at {angles[2]}°! (distance = {distances[2]})')
            
            elif distances[3] < SAFE_STOP_DISTANCE: # 90°-120°
                twist.linear.x, twist.angular.z = self.turn(RIGHT, distances[3], back_up = True)
                self._cmd_pub.publish(twist)
                rospy.loginfo(f'Too close at {angles[3]}°! (distance = {distances[3]})')
            
            elif distances[1] < SAFE_STOP_DISTANCE * 2: # 30°-60°
                twist.linear.x, twist.angular.z = self.turn(RIGHT, distances[1])
                self._cmd_pub.publish(twist)
                rospy.loginfo(f'Turn right, away from {angles[1]}°! (distance = {distances[1]})')
            
            elif distances[4] < SAFE_STOP_DISTANCE * 2: # 120°-150°
                twist.linear.x, twist.angular.z = self.turn(LEFT, distances[4])
                self._cmd_pub.publish(twist)
                rospy.loginfo(f'Turn left, away from {angles[4]}°! (distance = {distances[4]})')
            
            elif distances[0] < SAFE_STOP_DISTANCE: # 0°-30°
                twist.linear.x, twist.angular.z = self.turn(RIGHT, distances[0])
                self._cmd_pub.publish(twist)
                rospy.loginfo(f'Too close at {angles[0]}°! (distance = {distances[0]})')
            
            elif distances[5] < SAFE_STOP_DISTANCE: # 150°-180°
                twist.linear.x, twist.angular.z = self.turn(LEFT, distances[5])
                self._cmd_pub.publish(twist)
                rospy.loginfo(f'Too close at {angles[5]}°! (distance = {distances[5]})')

            else:
                twist.linear.x, twist.angular.z = LINEAR_VEL, 0
                self._cmd_pub.publish(twist)

            rospy.sleep(0.1)


def main():
    rospy.init_node('turtlebot3_obstacle')
    try:
        obstacle = Obstacle()
    except rospy.ROSInterruptException:
        pass

if __name__ == '__main__':
    main()
